const sidebars = {
  globalSidebar: [
    {
      type: 'category',
      label: 'Golden Path',
      items: [{ type: 'autogenerated', dirName: 'golden-path' }],
    },
    {
      type: 'category',
      label: 'Platform',
      items: [{ type: 'autogenerated', dirName: 'platform' }],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: 'Research',
      items: [{ type: 'autogenerated', dirName: 'research' }],
    },
  ],
  smallProjectsSidebar: [{ type: 'autogenerated', dirName: 'projects/small' }],
  saasProjectsSidebar: [{ type: 'autogenerated', dirName: 'projects/saas' }],
  enterpriseProjectsSidebar: [{ type: 'autogenerated', dirName: 'projects/enterprise' }],
};

module.exports = sidebars;
